# Generated by Django 4.1.7 on 2023-03-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_timestamp_article_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
